services:
  - type: web
    name: url-shortener-api
    runtime: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app

    # Attach a small persistent disk so SQLite survives deploys/restarts
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        # Use disk path so the DB persists
        value: sqlite:////opt/render/project/src/data/database.db
